[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dalla"
version = "0.1.0"
description = "Dalla AI Model"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.13"
authors = [
    { name = "Arab Center"},
]
keywords = ["nlp", "deep learning", "rlhf", "llm"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "accelerate>=1.9.0",
    "bitsandbytes>=0.46.1",
    "datasets>=4.0.0",
    "deepspeed>=0.17.2",
    "einops>=0.8.1",
    "evaluate==0.4.0",
    "huggingface-hub>=0.33.4,<1.0",
    "jinja2>=3.0.0",
    "liger-kernel>=0.6.0",
    "ninja>=1.11.1",
    "numpy>=1.24.2",
    "packaging>=23.0",
    "peft>=0.16.0",
    "protobuf<=3.20.2",
    "safetensors>=0.5.3",
    "sentencepiece>=0.2.0",
    "scipy",
    "tensorboard",
    "tqdm>=4.64.1",
    "transformers>=4.53.3",
    "trl<=0.19.1",
    "hf-transfer>=0.1.9",
    "wandb",
    "torch",
    "ray[train]>=2.10.0",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
]
torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
]
torchaudio = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
]

[project.optional-dependencies]
tests = ["pytest", "parameterized>=0.9.0"]
quality = ["black>=24.4.2", "isort>=5.12.0", "flake8>=6.0.0"]
docs = ["hf-doc-builder>=0.4.0"]
dev = ["alignment-handbook[docs,quality,tests]"]

[project.urls]
Homepage = "https://github.com/arab-center/dalla"

[tool.hatch.build.targets.wheel]
packages = ["src/alignment"]

[tool.isort]
default_section = "FIRSTPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = ["alignment"]
known_third_party = [
    "transformers",
    "datasets",
    "fugashi",
    "git",
    "h5py",
    "matplotlib",
    "nltk",
    "numpy",
    "packaging",
    "pandas",
    "psutil",
    "pytest",
    "rouge_score",
    "sacrebleu",
    "seqeval",
    "sklearn",
    "streamlit",
    "torch",
    "tqdm",
]
line_length = 119
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true

[tool.flake8]
ignore = ["E203", "E501", "E741", "W503", "W605"]
max-line-length = 119
per-file-ignores = ["__init__.py: F401"]

[tool.pytest.ini_options]
doctest_optionflags = ["NUMBER", "NORMALIZE_WHITESPACE", "ELLIPSIS"]
